# Generated by Django 5.2.8 on 2025-11-22 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_cart_cartitem'),
        ('wholesale', '0005_wholesaleorder_arrived_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_proxy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='proxy_wholesale_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proxied_products', to='wholesale.wholesaleproduct'),
        ),
    ]
