# Generated by Django 5.2.8 on 2025-11-19 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_cart_cartitem'),
        ('wholesale', '0002_wholesaleproduct_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='WholesaleCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_items', to='store.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wholesale.wholesaleproduct')),
            ],
            options={
                'unique_together': {('cart', 'product')},
            },
        ),
    ]
