# Generated by Django 5.2.8 on 2025-11-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0003_wholesalecartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesaleorder',
            name='addr_colony',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='wholesaleorder',
            name='addr_district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wholesaleorder',
            name='addr_house_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wholesaleorder',
            name='addr_pincode',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='wholesaleorder',
            name='addr_road_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='wholesaleorder',
            name='addr_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wholesaleorder',
            name='payment_mode',
            field=models.CharField(choices=[('Online', 'Online'), ('Cash on Delivery', 'Cash on Delivery')], default='Cash on Delivery', max_length=20),
        ),
        migrations.AddField(
            model_name='wholesaleorder',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='wholesaleorder',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wholesaleorder',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='wholesaleorder',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
