# Generated by Django 5.2.8 on 2025-11-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wholesale', '0004_wholesaleorder_addr_colony_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesaleorder',
            name='arrived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wholesaleorder',
            name='progress_stage',
            field=models.IntegerField(default=0),
        ),
    ]
