# Generated by Django 5.2.8 on 2025-11-20 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderfeedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfeedback',
            name='reply_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderfeedback',
            name='reply_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retailer_replies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderfeedback',
            name='reply_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
