# Generated by Django 5.2.8 on 2025-11-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderfeedback_reply_at_orderfeedback_reply_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='arrived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='progress_stage',
            field=models.IntegerField(default=0),
        ),
    ]
